### ISSUE TITLE
Sentence IDs

### ISSUE THREAD

**Issue by macleginn** [UniversalDependencies/UD_Polish-PUD#2]
Sentence IDs in this dataset are different from the standard ones. The readme states, "PUD-PL consists of 1000 Polish sentences (18,389 tokens) in the same order as in the PUD treebanks in other languages." However, not all PUD treebanks share the same order: Icelandic has a different one. Therefore, in order to collect all parallel sentences one has to use one procedure for everything + Icelandic (use IDs) and another for everything + Polish (use the order of every other dataset except for Icelandic). As IDs seem to be a more robust grouping method than the linear order, I am reporting this issue here.

**Comment by dan-zeman** [comment]
Fixed in dev, thanks for reporting.
